[WIP] Intro edits
worldbank/dime-data-handbook pull request #519
Opened 2020-09-17 19:06 UTC by mariaruth

2020-09-17 21:05 UTC, mariaruth commented
@bbdaniels i did quite a bit of reorganization to try to improve the logical flow of the sections and paragraphs, and overall make the intro tighter. please read and let me know what you think.

2020-09-18 11:21 UTC, bbdaniels requested changes
I think this looks great! Only two very minor edits.

2020-09-18 11:21 UTC, bbdaniels commented on chapters/0-introduction.tex
> +Despite the growing importance, little practical guidance is available for practitioners
```suggestion
Despite the growing importance of managing data work, 
little practical guidance is available for practitioners
```

2020-09-18 11:21 UTC, bbdaniels commented on chapters/0-introduction.tex
> +The DIME Analytics Resources Appendix provides an introduction to public materials.
```suggestion
The DIME Analytics Resource Directory appendix provides an introduction to public materials.
```

2020-09-18 13:26 UTC, mariaruth commented
@bbdaniels - i accepted both changes, if nothing else let's merge this

2020-09-18 14:50 UTC, bbdaniels approved these changes

2020-09-18 14:51 UTC, merged